### ISSUE TITLE
403 Client Error: Forbidden ...

### ISSUE THREAD

**Issue by juergen88400** [erikkastelec/hass-WEM-Portal#102]
it used to work until today about 16:00 CET
no change to my best knowledge
did already several reboots, new pull of hass-WEM-Portal
error persists

This is an excerpt of my logfile:

2024-10-10 17:54:50.914 WARNING (MainThread) [custom_components.wemportal] Creating new wemportal api instance
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 195, in api_login
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.wemportal.com/app/Account/Login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 88, in fetch_data
    self.api_login()
  File "/config/custom_components/wemportal/wemportalapi.py", line 208, in api_login
    raise ForbiddenError(
custom_components.wemportal.exceptions.ForbiddenError: WemPortal forbidden error: Server returned internal status code:  and message: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 47, in _async_update_data
    x = await self.hass.async_add_executor_job(self.api.fetch_data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wemportal/wemportalapi.py", line 142, in fetch_data
    raise WemPortalError from exc
custom_components.wemportal.exceptions.WemPortalError
2024-10-10 17:54:51.059 ERROR (MainThread) [custom_components.wemportal] Error fetching data from wemportal
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 195, in api_login
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.wemportal.com/app/Account/Login

**Comment by juergen88400** [comment]
took some 15-20 MInutes until it resolved "on its own"
closing this issue

**Comment by juergen88400** [comment]
took some 15-20 MInutes until it resolved "on its own"
closing this issue
