### ISSUE TITLE
Error setting up

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#103]
```
Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 16:00:29 (1 Vorkommnisse)
Zuletzt protokolliert: 16:00:29

Error setting up entry d@m.com.de for wemportal
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wemportal/__init__.py", line 106, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wemportal/coordinator.py", line 47, in _async_update_data
    x = await self.hass.async_add_executor_job(self.api.fetch_data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout

```

- app is working
- Web is working
- Integration is not, are they trying to work against the integration?

**Comment by dm82m** [comment]
Back working, maybe only a temporary problem
