### ISSUE TITLE
Setup failed after upgrading HA to 2024.11 (Docker/Kubernetes)

### ISSUE THREAD

**Issue by fenkman** [erikkastelec/hass-WEM-Portal#111]
I am running Kubernetes on K3S using this Helm chart: https://github.com/pajikos/home-assistant-helm-chart

After upgrading to the current image tag 2024.11, the integration no longer works, claiming a missing python module 'zope'.

Here is the log:

Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 09:44:14 (1 Vorkommnisse)
Zuletzt protokolliert: 09:44:14

Setup failed for custom integration 'wemportal': Unable to import component: No module named 'zope'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/wemportal/__init__.py", line 26, in <module>
    from .coordinator import WemPortalDataUpdateCoordinator
  File "/config/custom_components/wemportal/coordinator.py", line 15, in <module>
    from .wemportalapi import WemPortalApi
  File "/config/custom_components/wemportal/wemportalapi.py", line 13, in <module>
    import scrapyscript
  File "/config/deps/lib/python3.12/site-packages/scrapyscript/__init__.py", line 14, in <module>
    from scrapy import signals
  File "/config/deps/lib/python3.12/site-packages/scrapy/__init__.py", line 12, in <module>
    from scrapy.spiders import Spider
  File "/config/deps/lib/python3.12/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/config/deps/lib/python3.12/site-packages/scrapy/http/__init__.py", line 8, in <module>
    from scrapy.http.headers import Headers
  File "/config/deps/lib/python3.12/site-packages/scrapy/http/headers.py", line 5, in <module>
    from scrapy.utils.python import to_unicode
  File "/config/deps/lib/python3.12/site-packages/scrapy/utils/python.py", line 17, in <module>
    from scrapy.utils.decorators import deprecated
  File "/config/deps/lib/python3.12/site-packages/scrapy/utils/decorators.py", line 4, in <module>
    from twisted.internet import defer, threads
  File "/config/deps/lib/python3.12/site-packages/twisted/internet/defer.py", line 44, in <module>
    from twisted.internet.interfaces import IDelayedCall, IReactorTime
  File "/config/deps/lib/python3.12/site-packages/twisted/internet/interfaces.py", line 24, in <module>
    from zope.interface import Attribute, Interface
ModuleNotFoundError: No module named 'zope'

Is this an issue with the wemportal integration or rather something missing in the HA 2024.11 Docker image?

**Comment by fenkman** [comment]
I finally found out that this issue is not with the wemportal integration but a general issue with HA since version 2024.10 concerning python module requirements in containerized environments.
A workaround is described here: https://community.home-assistant.io/t/wth-is-going-on-with-docker-container-installs-and-third-party-integrations-that-need-python-modules/806430/6
For me, mounting a Kubernetes emptyDir at .dockerenv did the trick.
