### ISSUE TITLE
Update to 1.5.12 not working

### ISSUE THREAD

**Issue by dl1ekm** [erikkastelec/hass-WEM-Portal#116]
Hi,
although there is a version 1.5.12 in the repo and in HACS the WEM-Portal is in the "downloaded list" with this version, in devices and services the integration is still shown as "1.5.11". I've done soft and full restart of HA, HASS etc., downloaded twice again - nothing helped. Any idea?
BTW: The integration doesn't work since a couple of days - although I have no problems with the web-portal of WEM.
Is the internal updated blocked if there are startup errors in an older version?
Last error message in the logs (sounds similar to another open issue?):
```
Error fetching data from wemportal
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 254, in make_api_call
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.wemportal.com/app/EventType/Read

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 91, in fetch_data
    self.get_parameters()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/wemportal/wemportalapi.py", line 311, in get_parameters
    response = self.make_api_call(
        "https://www.wemportal.com/app/EventType/Read", data=data
    )
  File "/config/custom_components/wemportal/wemportalapi.py", line 269, in make_api_call
    raise WemPortalError(
        f"{DATA_GATHERING_ERROR} Server returned status code: {server_status} and message: {server_message}"
    ) from exc
custom_components.wemportal.exceptions.WemPortalError: An error occurred while gathering data.This issue should resolve by itself. If this problem persists,open an issue at https://github.com/erikkastelec/hass-WEM-Portal/issues Server returned status code:  and message: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 67, in _async_update_data
    x = await self.hass.async_add_executor_job(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.fetch_data
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wemportal/wemportalapi.py", line 142, in fetch_data
    raise WemPortalError from exc
custom_components.wemportal.exceptions.WemPortalError
```

**Comment by dm82m** [comment]
403 issue is discussed in #96

**Comment by dm82m** [comment]
regarding version, @erikkastelec just forget to set the internal version number. the version you see in hacs is the version you are using, just ignore the one that HA shows in integrations. we will fix it with the next release.

**Comment by dl1ekm** [comment]
Thanks!
