### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#2]
Started the component but got an IndexError. Let me know if you need anything for debugging.

```
Logger: wemportal
Source: custom_components/wemportal/wemportalapi.py:27
First occurred: 12:13:34 (1 occurrences)
Last logged: 12:13:34

Unexpected error fetching wem_portal_sensor data: list index out of range
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
    return await self.update_method()
  File "/home/homeassistant/.homeassistant/custom_components/wemportal/sensor.py", line 385, in async_update_data
    data = await hass.async_add_executor_job(api.fetch_data)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/wemportal/wemportalapi.py", line 27, in fetch_data
    data = processor.run([wemportalJob])[0]
IndexError: list index out of range

```

And that leads to:

```
Logger: homeassistant.components.sensor
Source: custom_components/wemportal/sensor.py:467
Integration: Sensor (documentation, issues)
First occurred: 12:13:34 (1 occurrences)
Last logged: 12:13:34

Error while setting up wemportal platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/homeassistant/.homeassistant/custom_components/wemportal/sensor.py", line 409, in async_setup_platform
    entities.append(WemPortalSensor(coordinator, sensor_type, sensor_prefix))
  File "/home/homeassistant/.homeassistant/custom_components/wemportal/sensor.py", line 428, in __init__
    self._state = self.state
  File "/home/homeassistant/.homeassistant/custom_components/wemportal/sensor.py", line 467, in state
    state = self.coordinator.data[self.type]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by erikkastelec** [comment]
I encountered that error when I entered a wrong password. If your password contains any special characters, write it in quotes. 

Will add proper logs for failed authentication.

**Comment by dm82m** [comment]
tried it with quoted password, same problem. my username is a mail address and contains an @ - also quoted that but still the exact same log output...

**Comment by dm82m** [comment]
Also removed all special characters from my password, so only upper lower case and numbers but still the same problem

**Comment by erikkastelec** [comment]
I guess there is something else going on. Will try to debug it now and will let you know if I need any additional information.

Thank you for your patience

**Comment by erikkastelec** [comment]
I couldn't find anything obvious that could cause the issue but made some changes with logging. It would be helpful if you set component logging to debug and post the logs. UI does not allow you to see all the logs, so I suggest you take a look at the log file, where the whole output should be visible.

**Comment by dm82m** [comment]
Nothing really new. Yes the log output changed now but also not pointing into another direction than "IndexError: list index out of range"...

```
2021-02-22 16:48:24 ERROR (SyncWorker_2) [wemportal] There was a problem with getting data from WEM Portal. If this problem persists, open an issue at https://github.com/erikkastelec/hass-WEM-Portal/issues
Traceback (most recent call last):
File "/home/homeassistant/.homeassistant/custom_components/wemportal/wemportalapi.py", line 29, in fetch_data
data = processor.run([wemportalJob])[0]
IndexError: list index out of range
2021-02-22 16:48:25 ERROR (MainThread) [wemportal] Unexpected error fetching wem_portal_sensor data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
self.data = await self._async_update_data()
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
return await self.update_method()
File "/home/homeassistant/.homeassistant/custom_components/wemportal/sensor.py", line 385, in async_update_data
data = await hass.async_add_executor_job(api.fetch_data)
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/homeassistant/.homeassistant/custom_components/wemportal/wemportalapi.py", line 34, in fetch_data
if data['authErrorFlag']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by erikkastelec** [comment]
Can you check your Home Assistant, scrapy and scrapyscript version for me. I tried to reproduce the bug with different versions, but didn't find anything.

Will try to get logs from spider to Home Assistant somehow, which are discarded because they come from scrapyscript. On docker I can get all the stdout logs, but as you are on hass core install (if I remember correctly) this does not work.

**Comment by dm82m** [comment]
```
Scrapy                  2.4.1
scrapyscript            1.1.0
```

I am just in a virtualenv, so should get all log output...

**Comment by dm82m** [comment]
I am on the newest version of HA. One strange thing, even with this configuration I do not get the debug messages:

```
logger:
  default: info
  logs:
    custom_components.wemportal: debug
```

**Comment by dm82m** [comment]
It seems that the processor is not getting initialized:

```
2021-02-23 12:23:26 DEBUG (SyncWorker_1) [wemportal] wemportalJob:
2021-02-23 12:23:26 DEBUG (SyncWorker_1) [wemportal] <scrapyscript.Job object at 0x6a5450a0>
2021-02-23 12:23:26 DEBUG (SyncWorker_1) [wemportal] processor:
```
Compared to Selenium - do I need to manually install a Scrapy or Scrapyscript exectuable in my system?

**Comment by erikkastelec** [comment]
I haven't found a solution for capturing logs from spider, but I added logging of HTML output from scraper in the latest release.
I suggest you update it and start hass manually from virtualenv with verbose logging and capture the output to file: 
`hass -v 2>&1 | tee logfile`
You can stop it after error occurs and upload the complete logs here or to pastebin.

**Comment by erikkastelec** [comment]
> Compared to Selenium - do I need to manually install a Scrapy or Scrapyscript exectuable in my system?
I did a fresh install of Ubuntu 18.04 and installed Home Assistant using virtualenv and everything seems to work fine. Full logs should provide us with some more information.

**Comment by dm82m** [comment]
is there a way to send you the pastebin link privately instead of sharing it public?

**Comment by dm82m** [comment]
https://gist.github.com/dm82m/dd55bb9d2a6fc162d48286061fb90544

**Comment by erikkastelec** [comment]
I see the issue. Will try to fix it and will let you know when you can test it.

**Comment by erikkastelec** [comment]
It should work now. Make sure to update your config, because resources field is not required anymore.

**Comment by dm82m** [comment]
Sadly not working:

```
2021-02-23 18:09:14 ERROR (SyncWorker_0) [custom_component.wemportal] There was a problem with getting data from WEM Portal. If this problem persists, open an issue at https://github.com/erikkastelec/hass-WEM-Portal/issues
Traceback (most recent call last):
File "/home/homeassistant/.homeassistant/custom_components/wemportal/wemportalapi.py", line 31, in fetch_data
data = processor.run([wemportalJob])[0]
IndexError: list index out of range
2021-02-23 18:09:14 ERROR (MainThread) [custom_component.wemportal] Unexpected error fetching wem_portal_sensor data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
self.data = await self._async_update_data()
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
return await self.update_method()
File "/home/homeassistant/.homeassistant/custom_components/wemportal/sensor.py", line 105, in async_update_data
data = await hass.async_add_executor_job(api.fetch_data)
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/homeassistant/.homeassistant/custom_components/wemportal/wemportalapi.py", line 36, in fetch_data
if data['authErrorFlag']:
TypeError: 'NoneType' object is not subscriptable
2021-02-23 18:09:14 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wemportal platform for sensor
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
await asyncio.shield(task)
File "/home/homeassistant/.homeassistant/custom_components/wemportal/sensor.py", line 124, in async_setup_platform
WemPortalSensor(coordinator, _name, values[1], values[2]) for _name, values in coordinator.data.items()
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by erikkastelec** [comment]
Some of the fields from your data contain name, but no data, which causes a crash while scraping. Will need to fix a few things to account for that.
I am testing on HTML from your log file now, so I can finally catch all the bugs.

**Comment by erikkastelec** [comment]
I tested it on your HTML and it seems to work ok now.

**Comment by dm82m** [comment]
that looks quite good though!

```
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_betriebsphase_wtc_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_betriebsphase_brenner_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_sollleistung_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_istleistung_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_vorlaufsolltemperatur_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_vorlauftemperatur_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_vorlauftemperatur_vpt_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_rucklauftemperatur_vpt_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_abgastemperatur_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_tageswarmemenge_vortag_gesamt_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_tageswarmemenge_vortag_heizbetrieb_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_tageswarmemenge_vortag_warmwasserbetrieb_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_zahler_seit_rucksetzen_brennerstarts_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_zahler_seit_rucksetzen_betriebsstunden_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_zahler_seit_rucksetzen_rucksetzen_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_gesamtzahler_brennerstarts_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_gesamtzahler_betriebsstunden_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_pumpenleistung_pumpe_intern_sollleistung_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_pumpenleistung_pumpe_intern_elektrische_leistung_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_pumpenleistung_pumpe_intern_betriebsart_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_volumenstrom_vpt_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_warmeleistung_vpt_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_anlagendruck_vpt_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_ionisationssignal_scot_basiswert_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_ionisationssignal_sollwert_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_ionisationssignal_scot_istwert_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_ionisationssignal_start_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_gasventil_offset_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_zeit_bis_flammenbildung_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_gasventil_ansteuersignal_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_gas_luft_verhaltnis_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_geblasedrehzahl_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.system_warmeanforderung_heizkreis_2_geblase_ansteuersignal_aktuell_we0
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.wtc_g_pc_weichentemperatur_aktuell
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_betriebsart
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_status
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_aussentemperatur_lokal_gemittelt
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_aussentemperatur_lokal_gemischt
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_aussentemperatur_aktuell
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_raumsolltemperatur_aktuell
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_vorlaufsolltemperatur_aktuell
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_vorlauftemperatur_aktuell_hzk1
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_mischerstellung_soll_aktuell
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_mischerstellung_ist_aktuell
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_pumpe_heizkreis
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_korrektur_aufheizoptimierung_letzte_optimierung
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_korrektur_aufheizoptimierung_korrektur_aktuell
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.hydraulik_korrektur_aufheizoptimierung_rucksetzen
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.heizkreis_heizkreise_heizkreis_1_status
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.heizkreis_heizkreise_heizkreis_1_warmwassersolltemperatur_aktuell
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.heizkreis_heizkreise_heizkreis_1_warmwassertemperatur_aktuell
2021-02-23 20:37:57 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wemportal entity: sensor.heizkreis_heizkreise_heizkreis_1_pumpe_warmwasser
```

**Comment by dm82m** [comment]
tiny cosmetics, some friendly names are looking a bit weird:

```
heizkreis/*+/*heizkreise_-_heizkreis_1-pumpe_warmwasser
heizkreis/*+/*heizkreise_-_heizkreis_1-status
heizkreis/*+/*heizkreise_-_heizkreis_1-warmwassersolltemperatur_aktuell
heizkreis/*+/*heizkreise_-_heizkreis_1-warmwassertemperatur_aktuell
wtc-g_/#pc/#-weichentemperatur_aktuell
```

but apart from that I am getting the values and that is brilliant! :)

**Comment by erikkastelec** [comment]
Fixed the names, but probably won't try to make them pretty, as it would take too much time, due to all the exceptions.
I changed them in the Home Assistant GUI, which takes some time, but is worth it in the end.

**Comment by dm82m** [comment]
THANK YOU VERY MUCH! Really great work! Much appreciated!
