### ISSUE TITLE
Sensors missing after update to 2022.11

### ISSUE THREAD

**Issue by sentinel43** [erikkastelec/hass-WEM-Portal#39]
Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221102.1 - latest

This error originated from a custom integration.

Logger: custom_components.wemportal
Source: custom_components/wemportal/wemportalapi.py:71
Integration: Weishaupt WEM Portal (documentation, issues)
First occurred: 3 November 2022 at 23:10:45 (19 occurrences)
Last logged: 08:20:22

There was a problem with getting data from WEM Portal. If this problem persists, open an issue at https://github.com/erikkastelec/hass-WEM-Portal/issues
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 71, in fetch_webscraping_data
    self.data = processor.run([wemportal_job])[0]
IndexError: list index out of range

**Comment by erikkastelec** [comment]
New version has been released. Let me know if this solves the issue

**Comment by PioSkot** [comment]
After the upgrade and physically even disabling Rasp.
1. 
Logger: homeassistant.setup
Source: helpers/update_coordinator.py:178
First occurred: 10:49:42 (1 occurrences)
Last logged: 10:49:42

Error during setup of component wemportal
Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 29, in _async_update_data
    return await self.hass.async_add_executor_job(self.api.fetch_data)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/wemportal/coordinator.py", line 28, in _async_update_data
    async with async_timeout.timeout(DEFAULT_TIMEOUT):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/wemportal/__init__.py", line 65, in async_setup
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady

2. 

Logger: custom_components.wemportal
Source: custom_components/wemportal/wemportalapi.py:71
Integration: Weishaupt WEM Portal ([documentation](https://github.com/erikkastelec/hass-WEM-Portal), [issues](https://github.com/erikkastelec/hass-WEM-Portal/issues))
First occurred: 10:47:44 (1 occurrences)
Last logged: 10:47:44

There was a problem with getting data from WEM Portal. If this problem persists, open an issue at https://github.com/erikkastelec/hass-WEM-Portal/issues
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 71, in fetch_webscraping_data
    self.data = processor.run([wemportal_job])[0]
IndexError: list index out of range

**Comment by oestreicher42** [comment]
I had the same error.
After upgrade I get the following new error:

2022-11-04 10:50:11.584 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration wemportal which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-04 10:50:38.393 ERROR (SyncWorker_2) [custom_components.wemportal] There was a problem with getting data from WEM Portal. If this problem persists, open an issue at https://github.com/erikkastelec/hass-WEM-Portal/issues
File "/config/custom_components/wemportal/wemportalapi.py", line 71, in fetch_webscraping_data
self.data = processor.run([wemportal_job])[0]
2022-11-04 10:50:38.926 DEBUG (SyncWorker_2) [custom_components.wemportal] Fetching api device data
2022-11-04 10:50:42.049 DEBUG (SyncWorker_2) [custom_components.wemportal] Fetching api parameters data
2022-11-04 10:50:47.675 WARNING (MainThread) [homeassistant.setup] Setup of wemportal is taking over 10 seconds.
2022-11-04 10:51:05.142 DEBUG (SyncWorker_2) [custom_components.wemportal] Fetching fresh api data
2022-11-04 10:51:20.276 ERROR (MainThread) [custom_components.wemportal] Unexpected error fetching WemPortal update data: 'Modules'
File "/config/custom_components/wemportal/coordinator.py", line 29, in _async_update_data
File "/config/custom_components/wemportal/wemportalapi.py", line 60, in fetch_data
File "/config/custom_components/wemportal/wemportalapi.py", line 94, in fetch_api_data
File "/config/custom_components/wemportal/wemportalapi.py", line 271, in get_data
2022-11-04 10:51:20.281 DEBUG (MainThread) [custom_components.wemportal] Finished fetching WemPortal update data in 42.608 seconds (success: False)
2022-11-04 10:51:20.282 ERROR (MainThread) [homeassistant.setup] Error during setup of component wemportal
File "/config/custom_components/wemportal/coordinator.py", line 29, in _async_update_data
File "/config/custom_components/wemportal/wemportalapi.py", line 60, in fetch_data
File "/config/custom_components/wemportal/wemportalapi.py", line 94, in fetch_api_data
File "/config/custom_components/wemportal/wemportalapi.py", line 271, in get_data
File "/config/custom_components/wemportal/__init__.py", line 65, in async_setup

I rebooted the whole server.
I am running the most recent version of home assistant.

**Comment by erikkastelec** [comment]
Should be fixed now.

**Comment by oestreicher42** [comment]
confirmed

**Comment by PioSkot** [comment]
Now:

Logger: homeassistant.setup
Source: helpers/update_coordinator.py:178
First occurred: 14:15:51 (1 occurrences)
Last logged: 14:15:51

Error during setup of component wemportal
Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 29, in _async_update_data
    return await self.hass.async_add_executor_job(self.api.fetch_data)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/wemportal/coordinator.py", line 28, in _async_update_data
    async with async_timeout.timeout(DEFAULT_TIMEOUT):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/wemportal/__init__.py", line 65, in async_setup
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady

**Comment by SKis274** [comment]
I confirmed that it's fixed now. All sensors are available again. Thanks a lot!
