### ISSUE TITLE
Error after update from 1.3.14 to 1.3.15

### ISSUE THREAD

**Issue by sentinel43** [erikkastelec/hass-WEM-Portal#41]
Logger: homeassistant.setup
Source: helpers/update_coordinator.py:178
First occurred: 14:08:40 (1 occurrences)
Last logged: 14:08:40

Error during setup of component wemportal
Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 29, in _async_update_data
    return await self.hass.async_add_executor_job(self.api.fetch_data)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/wemportal/coordinator.py", line 28, in _async_update_data
    async with async_timeout.timeout(DEFAULT_TIMEOUT):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/wemportal/__init__.py", line 65, in async_setup
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady

EDIT: Full shutdown and reboot performed and now working, sorry, cant delete it.

**Comment by erikkastelec** [comment]
This is the same error as the one in issue #36, so we can continue discussion there. A new version has been released, which should mitigate this.
