### ISSUE TITLE
API failure on component start

### ISSUE THREAD

**Issue by erikkastelec** [erikkastelec/hass-WEM-Portal#55]
Since I did the upgrade to the last version I have this error message:  Can somebody help me ? 
The web part is working when I put in the config file web but if I use API or both I have this . 
I was using the API since sometimes now without any problem.

I tried to increase the time out but it didn't help.

thanks

Error during setup of component wemportal
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/wemportal/coordinator.py", line 29, in _async_update_data
    return await self.hass.async_add_executor_job(self.api.fetch_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wemportal/wemportalapi.py", line 60, in fetch_data
    self.fetch_api_data()
  File "/config/custom_components/wemportal/wemportalapi.py", line 94, in fetch_api_data
    self.get_data()
  File "/config/custom_components/wemportal/wemportalapi.py", line 265, in get_data
    ).json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/wemportal/__init__.py", line 65, in async_setup
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 211, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Expecting value: line 1 column 1 (char 0)

_Originally posted by @dilki001 in https://github.com/erikkastelec/hass-WEM-Portal/issues/36#issuecomment-1483770807_

**Comment by erikkastelec** [comment]
@dilki001 I created a new release. Please update and  change logging level to debug (instructions are in the README of this project). This way I can get a better idea of what the issue could be.

**Comment by dilki001** [comment]
2023-03-26 20:30:21.055 DEBUG (SyncWorker_4) [custom_components.wemportal] Fetching api device data
2023-03-26 20:30:21.234 DEBUG (SyncWorker_4) [custom_components.wemportal] Fetching api parameters data
2023-03-26 20:30:28.093 DEBUG (SyncWorker_4) [custom_components.wemportal] Fetching fresh api data
2023-03-26 20:30:50.104 DEBUG (SyncWorker_4) [custom_components.wemportal] {(0, 1): {'Index': 0, 'Type': 1, 'Name': 'SYSTEM0', 'parameters': {'Außentemperatur': {'ParameterID': 'Außentemperatur', 'Name': 'T° extérieure Actuel', 'DataType': 3, 'MinValue': -100.0, 'MaxValue': 100.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}}}, (0, 2): {'Index': 0, 'Type': 2, 'Name': 'HZK0', 'parameters': {'Raumtemperatur': {'ParameterID': 'Raumtemperatur', 'Name': 'T° ambiante 1 Actuel', 'DataType': 3, 'MinValue': -100.0, 'MaxValue': 100.0, 'DefaultValue': '200', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}, 'Betriebsart': {'ParameterID': 'Betriebsart', 'Name': 'Mode', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '2', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 1, 'Name': 'Standby'}, {'Value': 2, 'Name': 'Programme horaire 1'}, {'Value': 3, 'Name': 'Programme horaire 2'}, {'Value': 4, 'Name': 'Programme horaire 3'}, {'Value': 5, 'Name': 'Eté'}, {'Value': 6, 'Name': 'Confort'}, {'Value': 7, 'Name': 'Normal'}, {'Value': 8, 'Name': 'Réduit'}]}, 'Heizprogramm1': {'ParameterID': 'Heizprogramm1', 'Name': 'Programme horaire 1', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Heizprogramm2': {'ParameterID': 'Heizprogramm2', 'Name': 'Programme horaire 2', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Heizprogramm3': {'ParameterID': 'Heizprogramm3', 'Name': 'Programme horaire 3', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'PP_Funktion': {'ParameterID': 'PP_Funktion', 'Name': 'Fête / Absence Fonction', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 0, 'Name': 'OFF'}, {'Value': 1, 'Name': 'Fête / Absence'}, {'Value': 2, 'Name': 'Absence'}]}, 'PP_Raumsoll': {'ParameterID': 'PP_Raumsoll', 'Name': 'Fête / Absence Consigne T° ambiante', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '1', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 1, 'Name': 'Réduit'}, {'Value': 2, 'Name': 'Normal'}, {'Value': 3, 'Name': 'Confort'}]}, 'PP_Beginn': {'ParameterID': 'PP_Beginn', 'Name': '@@wh-511-ET-Name-Dummy-3', 'DataType': 2, 'MinValue': 0.0, 'MaxValue': 59.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'PP_Ende': {'ParameterID': 'PP_Ende', 'Name': '@@wh-511-ET-Name-Dummy-3', 'DataType': 2, 'MinValue': 0.0, 'MaxValue': 59.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Komfort': {'ParameterID': 'Komfort', 'Name': 'T° consigne~ ambiance Confort', 'DataType': 3, 'MinValue': 5.0, 'MaxValue': 35.0, 'DefaultValue': '220', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Normal': {'ParameterID': 'Normal', 'Name': 'T° consigne~ ambiance Normal', 'DataType': 3, 'MinValue': 5.0, 'MaxValue': 35.0, 'DefaultValue': '210', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Absenk': {'ParameterID': 'Absenk', 'Name': 'T° consigne~ ambiance Réduit', 'DataType': 3, 'MinValue': 5.0, 'MaxValue': 35.0, 'DefaultValue': '160', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'U_Funktion': {'ParameterID': 'U_Funktion', 'Name': 'Vacances Fonction', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 0, 'Name': 'OFF'}, {'Value': 1, 'Name': 'ON'}]}, 'U_Raumsoll': {'ParameterID': 'U_Raumsoll', 'Name': 'Vacances Consigne T° ambiante', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 0, 'Name': 'Hors-gel'}, {'Value': 1, 'Name': 'Réduit'}]}, 'U_Beginn': {'ParameterID': 'U_Beginn', 'Name': '@@wh-511-ET-Name-Dummy-4', 'DataType': 2, 'MinValue': 1.0, 'MaxValue': 31.0, 'DefaultValue': '1', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'U_Ende': {'ParameterID': 'U_Ende', 'Name': '@@wh-511-ET-Name-Dummy-4', 'DataType': 2, 'MinValue': 1.0, 'MaxValue': 31.0, 'DefaultValue': '1', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'AktRaumSoll': {'ParameterID': 'AktRaumSoll', 'Name': 'Consigne T° ambiante Actuel', 'DataType': 3, 'MinValue': -100.0, 'MaxValue': 100.0, 'DefaultValue': '200', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}}}, (0, 3): {'Index': 0, 'Type': 3, 'Name': 'WW0', 'parameters': {'Warmwassertemperatur': {'ParameterID': 'Warmwassertemperatur', 'Name': 'T° ECS Actuel', 'DataType': 3, 'MinValue': -40.0, 'MaxValue': 150.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}, 'NormalWW': {'ParameterID': 'NormalWW', 'Name': 'Consigne T° ECS Normal', 'DataType': 3, 'MinValue': 0.0, 'MaxValue': 100.0, 'DefaultValue': '500', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'AbsenkWW': {'ParameterID': 'AbsenkWW', 'Name': 'Consigne T° ECS Réduit', 'DataType': 3, 'MinValue': 0.0, 'MaxValue': 100.0, 'DefaultValue': '400', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'WW-Push': {'ParameterID': 'WW-Push', 'Name': 'Relance ECS', 'DataType': 2, 'MinValue': 0.0, 'MaxValue': 1.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'WW-Programm': {'ParameterID': 'WW-Programm', 'Name': 'Programme ECS', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Zirkulationsprogramm': {'ParameterID': 'Zirkulationsprogramm', 'Name': 'Programme bouclage ECS', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}}}, (0, 7): {'Index': 0, 'Type': 7, 'Name': 'WE0', 'parameters': {'Leistung': {'ParameterID': 'Leistung', 'Name': 'Puissance instantanée Actuel', 'DataType': 3, 'MinValue': 0.0, 'MaxValue': 200.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}, 'Vorlauftemperatur': {'ParameterID': 'Vorlauftemperatur', 'Name': 'T° départ Actuel', 'DataType': 3, 'MinValue': -6.0, 'MaxValue': 16.0, 'DefaultValue': '25', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}, 'Anlagendruck': {'ParameterID': 'Anlagendruck', 'Name': 'Pression installation VPT Actuel', 'DataType': 3, 'MinValue': 0.0, 'MaxValue': -0.01, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}, 'WW-Solltemp': {'ParameterID': 'WW-Solltemp', 'Name': 'Consigne de température ECS Normal', 'DataType': 3, 'MinValue': 30.0, 'MaxValue': 75.0, 'DefaultValue': '500', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}}}, (1, 2): {'Index': 1, 'Type': 2, 'Name': 'HZK1', 'parameters': {'Raumtemperatur': {'ParameterID': 'Raumtemperatur', 'Name': 'T° ambiante 1 Actuel', 'DataType': 3, 'MinValue': -100.0, 'MaxValue': 100.0, 'DefaultValue': '200', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}, 'Betriebsart': {'ParameterID': 'Betriebsart', 'Name': 'Mode', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '2', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 1, 'Name': 'Standby'}, {'Value': 2, 'Name': 'Programme horaire 1'}, {'Value': 3, 'Name': 'Programme horaire 2'}, {'Value': 4, 'Name': 'Programme horaire 3'}, {'Value': 5, 'Name': 'Eté'}, {'Value': 6, 'Name': 'Confort'}, {'Value': 7, 'Name': 'Normal'}, {'Value': 8, 'Name': 'Réduit'}]}, 'Heizprogramm1': {'ParameterID': 'Heizprogramm1', 'Name': 'Programme horaire 1', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Heizprogramm2': {'ParameterID': 'Heizprogramm2', 'Name': 'Programme horaire 2', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Heizprogramm3': {'ParameterID': 'Heizprogramm3', 'Name': 'Programme horaire 3', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'PP_Funktion': {'ParameterID': 'PP_Funktion', 'Name': 'Fête / Absence Fonction', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 0, 'Name': 'OFF'}, {'Value': 1, 'Name': 'Fête / Absence'}, {'Value': 2, 'Name': 'Absence'}]}, 'PP_Raumsoll': {'ParameterID': 'PP_Raumsoll', 'Name': 'Fête / Absence Consigne T° ambiante', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '1', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 1, 'Name': 'Réduit'}, {'Value': 2, 'Name': 'Normal'}, {'Value': 3, 'Name': 'Confort'}]}, 'PP_Beginn': {'ParameterID': 'PP_Beginn', 'Name': '@@wh-511-ET-Name-Dummy-3', 'DataType': 2, 'MinValue': 0.0, 'MaxValue': 59.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'PP_Ende': {'ParameterID': 'PP_Ende', 'Name': '@@wh-511-ET-Name-Dummy-3', 'DataType': 2, 'MinValue': 0.0, 'MaxValue': 59.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Komfort': {'ParameterID': 'Komfort', 'Name': 'T° consigne~ ambiance Confort', 'DataType': 3, 'MinValue': 5.0, 'MaxValue': 35.0, 'DefaultValue': '220', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Normal': {'ParameterID': 'Normal', 'Name': 'T° consigne~ ambiance Normal', 'DataType': 3, 'MinValue': 5.0, 'MaxValue': 35.0, 'DefaultValue': '210', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Absenk': {'ParameterID': 'Absenk', 'Name': 'T° consigne~ ambiance Réduit', 'DataType': 3, 'MinValue': 5.0, 'MaxValue': 35.0, 'DefaultValue': '160', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'U_Funktion': {'ParameterID': 'U_Funktion', 'Name': 'Vacances Fonction', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 0, 'Name': 'OFF'}, {'Value': 1, 'Name': 'ON'}]}, 'U_Raumsoll': {'ParameterID': 'U_Raumsoll', 'Name': 'Vacances Consigne T° ambiante', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 0, 'Name': 'Hors-gel'}, {'Value': 1, 'Name': 'Réduit'}]}, 'U_Beginn': {'ParameterID': 'U_Beginn', 'Name': '@@wh-511-ET-Name-Dummy-4', 'DataType': 2, 'MinValue': 1.0, 'MaxValue': 31.0, 'DefaultValue': '1', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'U_Ende': {'ParameterID': 'U_Ende', 'Name': '@@wh-511-ET-Name-Dummy-4', 'DataType': 2, 'MinValue': 1.0, 'MaxValue': 31.0, 'DefaultValue': '1', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'AktRaumSoll': {'ParameterID': 'AktRaumSoll', 'Name': 'Consigne T° ambiante Actuel', 'DataType': 3, 'MinValue': -100.0, 'MaxValue': 100.0, 'DefaultValue': '200', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}}}, (2, 2): {'Index': 2, 'Type': 2, 'Name': 'HZK2', 'parameters': {'Raumtemperatur': {'ParameterID': 'Raumtemperatur', 'Name': 'T° ambiante 1 Actuel', 'DataType': 3, 'MinValue': -100.0, 'MaxValue': 100.0, 'DefaultValue': '200', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}, 'Betriebsart': {'ParameterID': 'Betriebsart', 'Name': 'Mode', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '2', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 1, 'Name': 'Standby'}, {'Value': 2, 'Name': 'Programme horaire 1'}, {'Value': 3, 'Name': 'Programme horaire 2'}, {'Value': 4, 'Name': 'Programme horaire 3'}, {'Value': 5, 'Name': 'Eté'}, {'Value': 6, 'Name': 'Confort'}, {'Value': 7, 'Name': 'Normal'}, {'Value': 8, 'Name': 'Réduit'}]}, 'Heizprogramm1': {'ParameterID': 'Heizprogramm1', 'Name': 'Programme horaire 1', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Heizprogramm2': {'ParameterID': 'Heizprogramm2', 'Name': 'Programme horaire 2', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Heizprogramm3': {'ParameterID': 'Heizprogramm3', 'Name': 'Programme horaire 3', 'DataType': 6, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'PP_Funktion': {'ParameterID': 'PP_Funktion', 'Name': 'Fête / Absence Fonction', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 0, 'Name': 'OFF'}, {'Value': 1, 'Name': 'Fête / Absence'}, {'Value': 2, 'Name': 'Absence'}]}, 'PP_Raumsoll': {'ParameterID': 'PP_Raumsoll', 'Name': 'Fête / Absence Consigne T° ambiante', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '1', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 1, 'Name': 'Réduit'}, {'Value': 2, 'Name': 'Normal'}, {'Value': 3, 'Name': 'Confort'}]}, 'PP_Beginn': {'ParameterID': 'PP_Beginn', 'Name': '@@wh-511-ET-Name-Dummy-3', 'DataType': 2, 'MinValue': 0.0, 'MaxValue': 59.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'PP_Ende': {'ParameterID': 'PP_Ende', 'Name': '@@wh-511-ET-Name-Dummy-3', 'DataType': 2, 'MinValue': 0.0, 'MaxValue': 59.0, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Komfort': {'ParameterID': 'Komfort', 'Name': 'T° consigne~ ambiance Confort', 'DataType': 3, 'MinValue': 5.0, 'MaxValue': 35.0, 'DefaultValue': '220', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Normal': {'ParameterID': 'Normal', 'Name': 'T° consigne~ ambiance Normal', 'DataType': 3, 'MinValue': 5.0, 'MaxValue': 35.0, 'DefaultValue': '210', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'Absenk': {'ParameterID': 'Absenk', 'Name': 'T° consigne~ ambiance Réduit', 'DataType': 3, 'MinValue': 5.0, 'MaxValue': 35.0, 'DefaultValue': '160', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'U_Funktion': {'ParameterID': 'U_Funktion', 'Name': 'Vacances Fonction', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 0, 'Name': 'OFF'}, {'Value': 1, 'Name': 'ON'}]}, 'U_Raumsoll': {'ParameterID': 'U_Raumsoll', 'Name': 'Vacances Consigne T° ambiante', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '0', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 0, 'Name': 'Hors-gel'}, {'Value': 1, 'Name': 'Réduit'}]}, 'U_Beginn': {'ParameterID': 'U_Beginn', 'Name': '@@wh-511-ET-Name-Dummy-4', 'DataType': 2, 'MinValue': 1.0, 'MaxValue': 31.0, 'DefaultValue': '1', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'U_Ende': {'ParameterID': 'U_Ende', 'Name': '@@wh-511-ET-Name-Dummy-4', 'DataType': 2, 'MinValue': 1.0, 'MaxValue': 31.0, 'DefaultValue': '1', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, 'AktRaumSoll': {'ParameterID': 'AktRaumSoll', 'Name': 'Consigne T° ambiante Actuel', 'DataType': 3, 'MinValue': -100.0, 'MaxValue': 100.0, 'DefaultValue': '200', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}}}}
2023-03-26 20:30:50.107 DEBUG (SyncWorker_4) [custom_components.wemportal] {}
2023-03-26 20:30:50.107 ERROR (SyncWorker_4) [custom_components.wemportal] No response from wemportal API server.
2023-03-26 20:30:50.113 DEBUG (MainThread) [custom_components.wemportal] Finished fetching WemPortal update data in 29.286 seconds (success: True)

**Comment by PioSkot** [comment]
Will it be possible to connect to the API, or change my lovelace?

**Comment by erikkastelec** [comment]
I will be releasing a new, improved version of the integration this week. Hopefully, it fixes this and some other bugs. Expect an update soon.

**Comment by erikkastelec** [comment]
There is a new release. You should update your instance and open a new issue if the problem persists.

**Comment by dilki001** [comment]
Thanks it works now .
