### ISSUE TITLE
Mode "web" not working after upgrading to config flow (as used in v1.5.x)

### ISSUE THREAD

**Issue by ghenzler** [erikkastelec/hass-WEM-Portal#95]
I have only now upgraded to latest version 1.5.6  (I was on 1.4.5 on manual configuration before). 

I have tested a bit back and forth, but when ever I use "both" or "web" the custom component does not load/initialise (Error "Failed setup, will retry" in UI). 

When using "api" it works (but then i'm missing crucial information that is only available via wemportal.de (and not via app). 

I get the error below in `fetch_webscraping_data` - to me it almost looks like some python dependencies did not get updated as they should - @erikkastelec do you have an idea on how to fix this the easiest?

```
2024-09-18 13:15:02.514 DEBUG (SyncWorker_0) [custom_components.wemportal] Sending POST request to https://www.wemportal.com/app/EventType/Read with headers: {'User-Agent': 'WeishauptWEMApp', 'X-Api-Version': '2.0.0.0', 'Accept': '*/*', 'Content-Type': 'application/json'} and data: {'DeviceID': 21787, 'ModuleIndex': 1, 'ModuleType': 2}
2024-09-18 13:15:02.767 DEBUG (SyncWorker_0) [custom_components.wemportal] <Response [200]>
2024-09-18 13:15:02.768 DEBUG (SyncWorker_0) [custom_components.wemportal] {'Parameters': [{'ParameterID': 'Heizprogramm1', 'Name': 'Heizprogramm1', 'DataType': 2, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, {'ParameterID': 'U_Beginn', 'Name': 'U_Beginn', 'DataType': 2, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, {'ParameterID': 'U_Ende', 'Name': 'U_Ende', 'DataType': 2, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, {'ParameterID': 'Raumtemperatur', 'Name': 'HK 1 Raumtemperatur', 'DataType': -1, 'MinValue': 0.0, 'MaxValue': 0.0, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': False, 'EnumValues': None}, {'ParameterID': 'AktRaumSoll', 'Name': 'HK 1 Raumsoll', 'DataType': -1, 'MinValue': 16.0, 'MaxValue': 28.0, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, {'ParameterID': 'Komfort', 'Name': 'HK1 Raum Komfort', 'DataType': -1, 'MinValue': 21.0, 'MaxValue': 28.0, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, {'ParameterID': 'Absenk', 'Name': 'HK 1 Raum Absenk', 'DataType': -1, 'MinValue': 16.0, 'MaxValue': 21.0, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, {'ParameterID': 'Normal', 'Name': 'HK 1 Raum Normal', 'DataType': -1, 'MinValue': 16.0, 'MaxValue': 22.0, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': None}, {'ParameterID': 'Betriebsart', 'Name': 'Systembetriebsart', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 1, 'Name': 'Heizen'}, {'Value': 3, 'Name': 'Sommer'}, {'Value': 4, 'Name': 'Standby'}, {'Value': 0, 'Name': 'Automatik'}, {'Value': 2, 'Name': 'Kühlen'}, {'Value': 5, 'Name': '2.  WEZ'}]}, {'ParameterID': 'PP_Funktion', 'Name': 'Party/Pause', 'DataType': 1, 'MinValue': None, 'MaxValue': None, 'DefaultValue': '', 'IsReadable': True, 'IsWriteable': True, 'EnumValues': [{'Value': 1, 'Name': 'Pausenzeit  12.0 h'}, {'Value': 2, 'Name': 'Pausenzeit  11.5 h'}, {'Value': 3, 'Name': 'Pausenzeit  11.0 h'}, {'Value': 4, 'Name': 'Pausenzeit  10.5 h'}, {'Value': 5, 'Name': 'Pausenzeit  10.0 h'}, {'Value': 6, 'Name': 'Pausenzeit  9.5 h'}, {'Value': 7, 'Name': 'Pausenzeit  9.0 h'}, {'Value': 8, 'Name': 'Pausenzeit  8.5 h'}, {'Value': 9, 'Name': 'Pausenzeit  8.0 h'}, {'Value': 10, 'Name': 'Pausenzeit  7.5 h'}, {'Value': 11, 'Name': 'Pausenzeit  7.0 h'}, {'Value': 12, 'Name': 'Pausenzeit  6.5 h'}, {'Value': 13, 'Name': 'Pausenzeit  6.0 h'}, {'Value': 14, 'Name': 'Pausenzeit  5.5 h'}, {'Value': 15, 'Name': 'Pausenzeit  5.0 h'}, {'Value': 16, 'Name': 'Pausenzeit  4.5 h'}, {'Value': 17, 'Name': 'Pausenzeit  4.0 h'}, {'Value': 18, 'Name': 'Pausenzeit  3.5 h'}, {'Value': 19, 'Name': 'Pausenzeit  3.0 h'}, {'Value': 20, 'Name': 'Pausenzeit  2.5 h'}, {'Value': 21, 'Name': 'Pausenzeit  2.0 h'}, {'Value': 22, 'Name': 'Pausenzeit  1.5 h'}, {'Value': 23, 'Name': 'Pausenzeit  1.0 h'}, {'Value': 24, 'Name': 'Pausenzeit  0.5 h'}, {'Value': 25, 'Name': 'Automatik'}, {'Value': 26, 'Name': 'Party  0.5 h'}, {'Value': 27, 'Name': 'Party  1.0 h'}, {'Value': 28, 'Name': 'Party  1.5 h'}, {'Value': 29, 'Name': 'Party  2.0 h'}, {'Value': 30, 'Name': 'Party  2.5 h'}, {'Value': 31, 'Name': 'Party  3.0 h'}, {'Value': 32, 'Name': 'Party  3.5 h'}, {'Value': 33, 'Name': 'Party  4.0 h'}, {'Value': 34, 'Name': 'Party  4.5 h'}, {'Value': 35, 'Name': 'Party  5.0 h'}, {'Value': 36, 'Name': 'Party  5.5 h'}, {'Value': 37, 'Name': 'Party  6.0 h'}, {'Value': 38, 'Name': 'Party  6.5 h'}, {'Value': 39, 'Name': 'Party  7.0 h'}, {'Value': 40, 'Name': 'Party  7.5 h'}, {'Value': 41, 'Name': 'Party  8.0 h'}, {'Value': 42, 'Name': 'Party  8.5 h'}, {'Value': 43, 'Name': 'Party  9.0 h'}, {'Value': 44, 'Name': 'Party  9.5 h'}, {'Value': 45, 'Name': 'Party  10.0 h'}, {'Value': 46, 'Name': 'Party  10.5 h'}, {'Value': 47, 'Name': 'Party  11.0 h'}, {'Value': 48, 'Name': 'Party  11.5 h'}, {'Value': 49, 'Name': 'Party  12.0 h'}]}], 'Status': 0, 'Message': None, 'DetailMessages': None}
2024-09-18 13:15:02.773 WARNING (MainThread) [custom_components.wemportal] Creating new wemportal api instance
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 96, in fetch_data
    # Get data by web scraping
                               
  File "/config/custom_components/wemportal/wemportalapi.py", line 149, in fetch_webscraping_data
    )
      
  File "/usr/local/lib/python3.12/site-packages/scrapyscript/__init__.py", line 51, in __init__
    self.results = Queue(**kwargs)
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/billiard/queues.py", line 45, in __init__
    self._rlock = ctx.Lock()
                  ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/billiard/context.py", line 105, in Lock
    return Lock(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/billiard/synchronize.py", line 182, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.12/site-packages/billiard/synchronize.py", line 71, in __init__
    sl = self._semlock = _billiard.SemLock(
                         ^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 47, in _async_update_data
    x = await self.hass.async_add_executor_job(self.api.fetch_data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wemportal/wemportalapi.py", line 142, in fetch_data
    except Exception as exc:
        ^^^^^^^^^^^^^^^^^^^^^
custom_components.wemportal.exceptions.WemPortalError
2024-09-18 13:15:02.779 DEBUG (MainThread) [custom_components.wemportal] Finished fetching WemPortal update data in 1.461 seconds (success: False)
```

**Comment by ghenzler** [comment]
My bad, after reading more in the existing issues I found `ha core rebuild` fixes the issue: 
https://github.com/erikkastelec/hass-WEM-Portal/issues/86#issuecomment-2050276804

**Comment by erikkastelec** [comment]
I am glad you got it working
